# Blueprint do Render para o projeto AgroMark
# Descreve a infraestrutura como código (IaC)

# 1. Definição do Banco de Dados
databases:
  - name: agromark-postgres
    databaseName: agromark
    plan: free # Importante: o plano gratuito pode "dormir" após inatividade
    postgresMajorVersion: 16

# 2. Definição dos Serviços Web (Frontend e Backend)
services:
  # Serviço do Backend (construído a partir do Dockerfile)
  - type: web
    name: agromark-backend
    plan: free
    env: docker
    dockerfilePath: ./backend/Dockerfile
    # Otimização: só reconstrói se houver mudanças na pasta 'backend/'
    buildFilter:
      paths:
      - backend/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agromark-postgres
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false # Importante: Será configurado manualmente no dashboard

  # Serviço do Frontend (construído a partir do Dockerfile)
  - type: web
    name: agromark-frontend
    plan: free
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    # Otimização: só reconstrói se houver mudanças na pasta 'frontend/'
    buildFilter:
      paths:
      - frontend/**
    # AVISO: A seção 'routes' foi removida. Regras de reescrita não são
    # suportadas para serviços do tipo 'docker' no Render. A comunicação
    # entre frontend e backend será feita via CORS no backend.
    envVars:
      - key: VITE_BACKEND_URL # Aponta para o serviço de backend
        value: "https://agromark-backend.onrender.com"